### ISSUE TITLE
Things to fix on authentication branch

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#72]
1. Fix the shell script error in `client/script/test.bash`
2. Remove hardcoding of authentication credentials in `client/test/e2e/playwright/auth.setup.js` by using [dotnev](https://github.com/motdotla/dotenv) package.
3. `client/test/README.md` explaining the steps required create a configuration file before running the end-to-end tests.
4. Make the end-to-end tests run in all browsers.
5. Revert all the changes done in `servers/` codebase.

**Comment by KarstenMalle** [comment]
@prasadtalasila 

1. Is fixed, this was due to a OR statement that has been removed as it was unnecessary.
2. Is done, now it requires the user/client to set up a .env file in /test to run the e2e tests.
3. Is done, README explains how to setup the .env file mentioned previously.
4. Test now also run in Chrome browser with no issues, I found a way to always setup the authentication process using Firefox so technically it should work on all browser, u can just install the ones u want using the npx playwright install command and then add them in the playwright config file.  
5. The changes done to the `server/` codebase are all coming from feature/distributed-demo so our code can be easily merged.

**Comment by prasadtalasila** [comment]
@KarstenMalle , the PR #72 is not there in the PRs. Can you open a new one? Thanks.

**Comment by prasadtalasila** [comment]
Also you keep merging the upstream into your commits. This just messes up a lot of things in the commits. Can you please [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) to authentication branch?

**Comment by KarstenMalle** [comment]
> @KarstenMalle , the PR #72 is not there in the PRs. Can you open a new one? Thanks.

Yes for sure, should it be for the `authentication` branch or `feature/distributed-demo`?

**Comment by prasadtalasila** [comment]
Let's do it to authentication branch. If it works, then we can merge `authentication` branch into `feature/distributed-demo` branch.

**Comment by prasadtalasila** [comment]
The only pending task is to merge the authentication branch into feature/distributed-demo branch.

**Comment by KarstenMalle** [comment]
Great, do you need me to rebase then?

**Comment by prasadtalasila** [comment]
Yes, please rebase in your fork and open a PR.

**Comment by prasadtalasila** [comment]
completed in PR #86
